# Generated by Django 3.1.2 on 2021-08-10 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210809_2152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='sufficiencyLevel',
        ),
    ]
