# Generated by Django 3.1.2 on 2021-08-10 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_studentprofile_sufficiencylevel'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='sufficiencyLevel',
            field=models.IntegerField(default=0),
        ),
    ]
