# Generated by Django 3.1.2 on 2021-08-08 17:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('challanges', '0004_completed_challange'),
    ]

    operations = [
        migrations.AddField(
            model_name='challanges',
            name='Assigned_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='challanges',
            name='last_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
