# Generated by Django 3.1.2 on 2021-08-09 13:04

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('challanges', '0006_auto_20210809_0559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challanges',
            name='Assigned_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 8, 9, 6, 4, 30, 218947)),
        ),
        migrations.CreateModel(
            name='DueChallenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.TextField(blank=True, default='', null=True)),
                ('students', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
