# Generated by Django 3.1.2 on 2021-08-09 13:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challanges', '0007_auto_20210809_0604'),
    ]

    operations = [
        migrations.RenameField(
            model_name='duechallenge',
            old_name='students',
            new_name='student',
        ),
        migrations.AlterField(
            model_name='challanges',
            name='Assigned_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 8, 9, 6, 8, 58, 631941)),
        ),
    ]
