# Generated by Django 3.1.2 on 2021-08-09 13:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challanges', '0008_auto_20210809_0609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challanges',
            name='Assigned_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 8, 9, 6, 36, 50, 386861)),
        ),
        migrations.AlterField(
            model_name='challanges',
            name='last_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
