# Generated by Django 3.1.2 on 2021-08-09 19:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challanges', '0010_auto_20210809_0657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challanges',
            name='Assigned_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 8, 9, 12, 16, 18, 437680)),
        ),
    ]
