# Generated by Django 3.1.2 on 2021-08-10 05:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challanges', '0014_auto_20210809_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challanges',
            name='Assigned_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 8, 10, 5, 30, 17, 376370)),
        ),
    ]
