# Generated by Django 3.1.2 on 2021-08-10 06:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challanges', '0016_auto_20210810_0531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challanges',
            name='Assigned_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 8, 10, 6, 37, 48, 975011)),
        ),
    ]
